# config/routes.yaml

index:
  path: /{_locale}
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

user_index:
  path: /{_locale}/admin/user
  controller: App\Controller\UserController::index
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

user_show:
  path: /{_locale}/user/show
  controller: App\Controller\UserController::show
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

user_new:
  path: /{_locale}/admin/user/new
  controller: App\Controller\UserController::new
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

user_orders:
  path: /{_locale}/user/orders
  controller: App\Controller\UserController::orders
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

app_login:
  path: /login
  controller: App\Controller\SecurityController:login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController:login

shop_index:
  path: /{_locale}/shop
  controller: App\Controller\ShopController::index
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

shop_search_all:
  path: /{_locale}/shop/search
  controller: App\Controller\ShopController::search
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

shop_search:
  path: /{_locale}/shop/search/{search}
  controller: App\Controller\ShopController::search
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

shop_department:
  path: /{_locale}/shop/department/{categoryId}
  controller: App\Controller\ShopController::department
  methods: GET|HEAD
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

cart_index:
  path: /{_locale}/cart
  controller: App\Controller\CartController::index
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

cart_nbProducts:
  path: /{_locale}/cart/nbProducts
  controller: App\Controller\CartController::nbProducts
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

cart_add:
  path: /{_locale}/cart/add/{productId}/{quantity}
  controller: App\Controller\CartController::add
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr
    quantity: 1

cart_remove:
  path: /{_locale}/cart/remove/{productId}/{quantity}
  controller: App\Controller\CartController::remove
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr
    quantity: 1

cart_delete:
  path: /{_locale}/cart/delete/{productId}
  controller: App\Controller\CartController::delete
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

cart_clear:
  path: /{_locale}/cart/clear
  controller: App\Controller\CartController::clear
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

cart_validation:
  path: /{_locale}/cart/validation
  controller: App\Controller\CartController::validation
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr

contact_index:
  path: /{_locale}/contact
  controller: App\Controller\ContactController::index
  requirements:
    _locale: "%app.supported_locales%"
  defaults:
    _locale: fr
